name: Build macOS Application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # THE BIG FIX: We are now using an Apple Silicon (ARM64) runner.
    # macos-14 is the current label for these M1-powered machines.
    runs-on: macos-14

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pyinstaller
          # We no longer need ARCHFLAGS because we are building natively.
          pip install -r requirements.txt

      - name: Run PyInstaller build
        # This will now run natively on an ARM64 machine.
        run: python3 build_macos.py

      - name: Zip the .app file
        # This step should now finally succeed.
        run: ditto -c -k --sequesterRsrc --keepParent dist/LaTeX-Inserter.app LaTeX-Inserter.zip
        
      - name: Upload macOS App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LaTeX-Inserter-MacOS-App-Apple-Silicon
          path: LaTeX-Inserter.zip
