name: Build macOS Application (Diagnostic Run)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-diagnostics:
    runs-on: macos-14

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: 1. Check Initial Machine Architecture
        run: |
          echo "--- Running 'uname -m' to see machine hardware ---"
          uname -m
          echo "--- Running 'arch' to see current execution architecture ---"
          arch

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 2. Check Python's Architecture
        run: |
          echo "--- Checking which python is being used ---"
          which python
          echo "--- Running 'arch' again to see if setup-python changed it ---"
          arch
          echo "--- Asking Python what architecture it thinks it is ---"
          python -c "import platform; print(platform.machine())"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pyinstaller
          pip install -r requirements.txt
      
      - name: 3. Check Architecture After Install
        run: |
           echo "--- Checking PyInstaller version and location ---"
           pip show pyinstaller
           echo "--- Checking architecture of a critical library (Qt) ---"
           # This command might be complex, but let's see what it finds
           find $(pip show pyqt5-qt5 | grep Location | awk '{print $2}') -name "Qt" -exec file {} \; || echo "Could not inspect Qt library"

      - name: Run PyInstaller build
        run: python3 build_macos.py

      - name: 4. Check Final Executable Architecture
        run: |
          echo "--- Checking the architecture of the final generated executable ---"
          # This is the most important check.
          file dist/LaTeX-Inserter.app/Contents/MacOS/LaTeX-Inserter
