# A descriptive name for your workflow
name: Build macOS Application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      # Step 1: Check out repository code
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up an x86_64 Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # THE FIX: Use a more flexible version specifier. 
          # This tells the action to find the latest available 3.11 patch version.
          python-version: '3.11'

      # Step 3: Install dependencies with the correct architecture
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pyinstaller
          # Set ARCHFLAGS to tell pip to fetch x86_64 packages.
          # This is still necessary and very important.
          export ARCHFLAGS="-arch x86_64"
          pip install -r requirements.txt

      # Step 4: Run your PyInstaller build script
      - name: Run PyInstaller build
        run: python3 build_macos.py

      # Step 5: Zip the .app file for upload
      - name: Zip the .app file
        run: ditto -c -k --sequesterRsrc --keepParent dist/LaTeX-Inserter.app LaTeX-Inserter.zip
        
      # Step 6: Upload the final artifact
      - name: Upload macOS App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LaTeX-Inserter-MacOS-App
          path: LaTeX-Inserter.zip
