name: Build macOS Application (Forced Intel)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # THE FIX: We force pip to only install x86_64 compatible packages.
      - name: Install dependencies with Forced x86_64 Arch
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pyinstaller
          # This environment variable is the key.
          export ARCHFLAGS="-arch x86_64"
          pip install -r requirements.txt

      - name: Run PyInstaller build
        run: python3 build_macos.py

      - name: Verify Final Executable Architecture
        run: |
          echo "--- Verifying architecture of all bundled Mach-O files ---"
          find dist/LaTeX-Inserter.app -type f -exec file {} \; | grep "Mach-O"

      - name: Zip the .app file
        run: ditto -c -k --sequesterRsrc --keepParent dist/LaTeX-Inserter.app LaTeX-Inserter.zip
        
      - name: Upload macOS App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LaTeX-Inserter-MacOS-App-Intel
          path: LaTeX-Inserter.zip
