name: Build macOS Application (Intel)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # Use an Intel-based runner
    runs-on: macos-13

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pyinstaller
          pip install -r requirements.txt

      - name: Run PyInstaller build
        # We use your simplified build_macos.py which builds a native app
        run: python3 build_macos.py

      - name: Zip the .app file
        run: ditto -c -k --sequesterRsrc --keepParent dist/LaTeX-Inserter.app LaTeX-Inserter.zip
        
      - name: Upload macOS App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LaTeX-Inserter-MacOS-App-Intel
          path: LaTeX-Inserter.zip
